### ISSUE TITLE
Choose the http server implementation

### ISSUE THREAD

**Issue by jdcoffre** [hgomez-sonarsource/Teddy#1]
Choose an existing http server lib that:
 - can handle authentication

**Comment by drautureau-sonarsource** [comment]
A quick research 
- [nickel](https://github.com/nickel-org/nickel.rs)
- [iron](https://github.com/iron/iron)

We are now evaluating iron which seems to be a good choice for the following reasons:
- well documentated
- lots of contribution
- based on [hyper](https://github.com/hyperium/hyper) which seems to be a reference

**Comment by drautureau-sonarsource** [comment]
Implemented using [iron](https://github.com/iron/iron)
